/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Truck_bicycle_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[3] = {0, 0, 0};

/* Truck_bicycle_expl_vde_forw:(i0[6],i1[6x6],i2[6x3],i3[3],i4[])->(o0[6],o1[6x6],o2[6x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=5.0000000000000000e-01;
  a2=arg[3]? arg[3][0] : 0;
  a3=tan(a2);
  a3=(a1*a3);
  a4=atan(a3);
  a5=arg[0]? arg[0][3] : 0;
  a6=(a4+a5);
  a7=cos(a6);
  a8=(a0*a7);
  if (res[0]!=0) res[0][0]=a8;
  a5=(a4+a5);
  a8=sin(a5);
  a9=(a0*a8);
  if (res[0]!=0) res[0][1]=a9;
  a9=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][2]=a9;
  a9=sin(a4);
  a10=(a0*a9);
  a11=4.;
  a10=(a10/a11);
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][4]=a10;
  a10=-6.4870000000000005e-01;
  a11=arg[0]? arg[0][5] : 0;
  a11=(a10*a11);
  a12=2.2896999999999998e+00;
  a11=(a11+a12);
  if (res[0]!=0) res[0][5]=a11;
  a11=arg[1]? arg[1][2] : 0;
  a12=(a7*a11);
  a13=sin(a6);
  a14=arg[1]? arg[1][3] : 0;
  a15=(a13*a14);
  a15=(a0*a15);
  a12=(a12-a15);
  if (res[1]!=0) res[1][0]=a12;
  a12=(a8*a11);
  a15=cos(a5);
  a14=(a15*a14);
  a14=(a0*a14);
  a12=(a12+a14);
  if (res[1]!=0) res[1][1]=a12;
  a12=0.;
  if (res[1]!=0) res[1][2]=a12;
  a14=2.5000000000000000e-01;
  a11=(a9*a11);
  a11=(a14*a11);
  if (res[1]!=0) res[1][3]=a11;
  if (res[1]!=0) res[1][4]=a12;
  a11=arg[1]? arg[1][5] : 0;
  a11=(a10*a11);
  if (res[1]!=0) res[1][5]=a11;
  a11=arg[1]? arg[1][8] : 0;
  a16=(a7*a11);
  a17=arg[1]? arg[1][9] : 0;
  a18=(a13*a17);
  a18=(a0*a18);
  a16=(a16-a18);
  if (res[1]!=0) res[1][6]=a16;
  a16=(a8*a11);
  a17=(a15*a17);
  a17=(a0*a17);
  a16=(a16+a17);
  if (res[1]!=0) res[1][7]=a16;
  if (res[1]!=0) res[1][8]=a12;
  a11=(a9*a11);
  a11=(a14*a11);
  if (res[1]!=0) res[1][9]=a11;
  if (res[1]!=0) res[1][10]=a12;
  a11=arg[1]? arg[1][11] : 0;
  a11=(a10*a11);
  if (res[1]!=0) res[1][11]=a11;
  a11=arg[1]? arg[1][14] : 0;
  a16=(a7*a11);
  a17=arg[1]? arg[1][15] : 0;
  a18=(a13*a17);
  a18=(a0*a18);
  a16=(a16-a18);
  if (res[1]!=0) res[1][12]=a16;
  a16=(a8*a11);
  a17=(a15*a17);
  a17=(a0*a17);
  a16=(a16+a17);
  if (res[1]!=0) res[1][13]=a16;
  if (res[1]!=0) res[1][14]=a12;
  a11=(a9*a11);
  a11=(a14*a11);
  if (res[1]!=0) res[1][15]=a11;
  if (res[1]!=0) res[1][16]=a12;
  a11=arg[1]? arg[1][17] : 0;
  a11=(a10*a11);
  if (res[1]!=0) res[1][17]=a11;
  a11=arg[1]? arg[1][20] : 0;
  a16=(a7*a11);
  a17=arg[1]? arg[1][21] : 0;
  a18=(a13*a17);
  a18=(a0*a18);
  a16=(a16-a18);
  if (res[1]!=0) res[1][18]=a16;
  a16=(a8*a11);
  a17=(a15*a17);
  a17=(a0*a17);
  a16=(a16+a17);
  if (res[1]!=0) res[1][19]=a16;
  if (res[1]!=0) res[1][20]=a12;
  a11=(a9*a11);
  a11=(a14*a11);
  if (res[1]!=0) res[1][21]=a11;
  if (res[1]!=0) res[1][22]=a12;
  a11=arg[1]? arg[1][23] : 0;
  a11=(a10*a11);
  if (res[1]!=0) res[1][23]=a11;
  a11=arg[1]? arg[1][26] : 0;
  a16=(a7*a11);
  a17=arg[1]? arg[1][27] : 0;
  a18=(a13*a17);
  a18=(a0*a18);
  a16=(a16-a18);
  if (res[1]!=0) res[1][24]=a16;
  a16=(a8*a11);
  a17=(a15*a17);
  a17=(a0*a17);
  a16=(a16+a17);
  if (res[1]!=0) res[1][25]=a16;
  if (res[1]!=0) res[1][26]=a12;
  a11=(a9*a11);
  a11=(a14*a11);
  if (res[1]!=0) res[1][27]=a11;
  if (res[1]!=0) res[1][28]=a12;
  a11=arg[1]? arg[1][29] : 0;
  a11=(a10*a11);
  if (res[1]!=0) res[1][29]=a11;
  a11=arg[1]? arg[1][32] : 0;
  a16=(a7*a11);
  a17=arg[1]? arg[1][33] : 0;
  a13=(a13*a17);
  a13=(a0*a13);
  a16=(a16-a13);
  if (res[1]!=0) res[1][30]=a16;
  a16=(a8*a11);
  a15=(a15*a17);
  a15=(a0*a15);
  a16=(a16+a15);
  if (res[1]!=0) res[1][31]=a16;
  if (res[1]!=0) res[1][32]=a12;
  a11=(a9*a11);
  a11=(a14*a11);
  if (res[1]!=0) res[1][33]=a11;
  if (res[1]!=0) res[1][34]=a12;
  a11=arg[1]? arg[1][35] : 0;
  a11=(a10*a11);
  if (res[1]!=0) res[1][35]=a11;
  a11=arg[2]? arg[2][2] : 0;
  a16=(a7*a11);
  a15=sin(a6);
  a17=arg[2]? arg[2][3] : 0;
  a13=(a15*a17);
  a13=(a0*a13);
  a16=(a16-a13);
  a6=sin(a6);
  a2=cos(a2);
  a2=casadi_sq(a2);
  a1=(a1/a2);
  a2=1.;
  a3=casadi_sq(a3);
  a3=(a2+a3);
  a1=(a1/a3);
  a6=(a6*a1);
  a6=(a0*a6);
  a16=(a16-a6);
  if (res[2]!=0) res[2][0]=a16;
  a16=cos(a5);
  a16=(a16*a1);
  a16=(a0*a16);
  a6=(a8*a11);
  a5=cos(a5);
  a17=(a5*a17);
  a17=(a0*a17);
  a6=(a6+a17);
  a16=(a16+a6);
  if (res[2]!=0) res[2][1]=a16;
  if (res[2]!=0) res[2][2]=a12;
  a4=cos(a4);
  a4=(a4*a1);
  a4=(a0*a4);
  a4=(a14*a4);
  a11=(a9*a11);
  a11=(a14*a11);
  a4=(a4+a11);
  if (res[2]!=0) res[2][3]=a4;
  if (res[2]!=0) res[2][4]=a12;
  a4=arg[2]? arg[2][5] : 0;
  a4=(a10*a4);
  if (res[2]!=0) res[2][5]=a4;
  a4=arg[2]? arg[2][8] : 0;
  a11=(a7*a4);
  a1=arg[2]? arg[2][9] : 0;
  a16=(a15*a1);
  a16=(a0*a16);
  a11=(a11-a16);
  if (res[2]!=0) res[2][6]=a11;
  a11=(a8*a4);
  a1=(a5*a1);
  a1=(a0*a1);
  a11=(a11+a1);
  if (res[2]!=0) res[2][7]=a11;
  if (res[2]!=0) res[2][8]=a2;
  a4=(a9*a4);
  a4=(a14*a4);
  if (res[2]!=0) res[2][9]=a4;
  if (res[2]!=0) res[2][10]=a12;
  a4=arg[2]? arg[2][11] : 0;
  a4=(a10*a4);
  if (res[2]!=0) res[2][11]=a4;
  a4=arg[2]? arg[2][14] : 0;
  a7=(a7*a4);
  a11=arg[2]? arg[2][15] : 0;
  a15=(a15*a11);
  a15=(a0*a15);
  a7=(a7-a15);
  if (res[2]!=0) res[2][12]=a7;
  a8=(a8*a4);
  a5=(a5*a11);
  a0=(a0*a5);
  a8=(a8+a0);
  if (res[2]!=0) res[2][13]=a8;
  if (res[2]!=0) res[2][14]=a12;
  a9=(a9*a4);
  a14=(a14*a9);
  if (res[2]!=0) res[2][15]=a14;
  if (res[2]!=0) res[2][16]=a2;
  a2=arg[2]? arg[2][17] : 0;
  a10=(a10*a2);
  if (res[2]!=0) res[2][17]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int Truck_bicycle_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Truck_bicycle_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Truck_bicycle_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Truck_bicycle_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Truck_bicycle_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Truck_bicycle_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Truck_bicycle_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Truck_bicycle_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Truck_bicycle_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Truck_bicycle_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Truck_bicycle_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Truck_bicycle_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Truck_bicycle_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Truck_bicycle_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Truck_bicycle_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Truck_bicycle_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Truck_bicycle_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
