/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[6] = {4, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[3] = {0, 1, 3};
static const casadi_int casadi_s2[9] = {4, 2, 0, 1, 4, 2, 0, 1, 2};
static const casadi_int casadi_s3[11] = {2, 4, 0, 1, 2, 4, 4, 1, 1, 0, 1};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s6[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};

/* rockit_model_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[7])->(o0[4],o1[4x4],o2[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, *w11=w+11, *w12=w+15, *w13=w+19, *w14=w+35, *w15=w+39, *w16=w+43, *w19=w+47, *w20=w+49, *w22=w+53, *w23=w+56, *w24=w+59, *w25=w+67;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[3][1] */
  w1 = arg[3] ? arg[3][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @4 = (@1*@3) */
  w4  = (w1*w3);
  /* #5: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #6: @6 = (@1*@5) */
  w6  = (w1*w5);
  /* #7: @7 = input[3][0] */
  w7 = arg[3] ? arg[3][0] : 0;
  /* #8: @8 = tan(@7) */
  w8 = tan( w7 );
  /* #9: @9 = (@1*@8) */
  w9  = (w1*w8);
  /* #10: @10 = 0 */
  w10 = 0.;
  /* #11: @11 = vertcat(@4, @6, @9, @10) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w10;
  /* #12: @12 = (@0*@11) */
  for (i=0, rr=w12, cs=w11; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #13: output[0][0] = @12 */
  casadi_copy(w12, 4, res[0]);
  /* #14: @13 = input[1][0] */
  casadi_copy(arg[1], 16, w13);
  /* #15: {@12, @14, @15, @16} = horzsplit(@13) */
  casadi_copy(w13, 4, w12);
  casadi_copy(w13+4, 4, w14);
  casadi_copy(w13+8, 4, w15);
  casadi_copy(w13+12, 4, w16);
  /* #16: {NULL, NULL, @4, @6} = vertsplit(@12) */
  w4 = w12[2];
  w6 = w12[3];
  /* #17: @12 = (@11*@6) */
  for (i=0, rr=w12, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #18: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #19: @9 = (@6*@4) */
  w9  = (w6*w4);
  /* #20: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #21: @9 = (-@9) */
  w9 = (- w9 );
  /* #22: @10 = cos(@2) */
  w10 = cos( w2 );
  /* #23: @4 = (@10*@4) */
  w4  = (w10*w4);
  /* #24: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #25: @17 = 00 */
  /* #26: @18 = 00 */
  /* #27: @19 = vertcat(@9, @4, @17, @18) */
  rr=w19;
  *rr++ = w9;
  *rr++ = w4;
  /* #28: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) (*rr++)  = (w0*(*cs++));
  /* #29: @20 = dense(@19) */
  casadi_densify(w19, casadi_s0, w20, 0);
  /* #30: @12 = (@12+@20) */
  for (i=0, rr=w12, cs=w20; i<4; ++i) (*rr++) += (*cs++);
  /* #31: output[1][0] = @12 */
  casadi_copy(w12, 4, res[1]);
  /* #32: {NULL, NULL, @9, @4} = vertsplit(@14) */
  w9 = w14[2];
  w4 = w14[3];
  /* #33: @14 = (@11*@4) */
  for (i=0, rr=w14, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w4);
  /* #34: @4 = (@6*@9) */
  w4  = (w6*w9);
  /* #35: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #36: @4 = (-@4) */
  w4 = (- w4 );
  /* #37: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #38: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #39: @17 = 00 */
  /* #40: @18 = 00 */
  /* #41: @19 = vertcat(@4, @9, @17, @18) */
  rr=w19;
  *rr++ = w4;
  *rr++ = w9;
  /* #42: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) (*rr++)  = (w0*(*cs++));
  /* #43: @12 = dense(@19) */
  casadi_densify(w19, casadi_s0, w12, 0);
  /* #44: @14 = (@14+@12) */
  for (i=0, rr=w14, cs=w12; i<4; ++i) (*rr++) += (*cs++);
  /* #45: output[1][1] = @14 */
  if (res[1]) casadi_copy(w14, 4, res[1]+4);
  /* #46: {NULL, NULL, @4, @9} = vertsplit(@15) */
  w4 = w15[2];
  w9 = w15[3];
  /* #47: @15 = (@11*@9) */
  for (i=0, rr=w15, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #48: @9 = (@6*@4) */
  w9  = (w6*w4);
  /* #49: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #50: @9 = (-@9) */
  w9 = (- w9 );
  /* #51: @4 = (@10*@4) */
  w4  = (w10*w4);
  /* #52: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #53: @17 = 00 */
  /* #54: @18 = 00 */
  /* #55: @19 = vertcat(@9, @4, @17, @18) */
  rr=w19;
  *rr++ = w9;
  *rr++ = w4;
  /* #56: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) (*rr++)  = (w0*(*cs++));
  /* #57: @14 = dense(@19) */
  casadi_densify(w19, casadi_s0, w14, 0);
  /* #58: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<4; ++i) (*rr++) += (*cs++);
  /* #59: output[1][2] = @15 */
  if (res[1]) casadi_copy(w15, 4, res[1]+8);
  /* #60: {NULL, NULL, @9, @4} = vertsplit(@16) */
  w9 = w16[2];
  w4 = w16[3];
  /* #61: @16 = (@11*@4) */
  for (i=0, rr=w16, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w4);
  /* #62: @6 = (@6*@9) */
  w6 *= w9;
  /* #63: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #64: @6 = (-@6) */
  w6 = (- w6 );
  /* #65: @10 = (@10*@9) */
  w10 *= w9;
  /* #66: @10 = (@1*@10) */
  w10  = (w1*w10);
  /* #67: @17 = 00 */
  /* #68: @18 = 00 */
  /* #69: @19 = vertcat(@6, @10, @17, @18) */
  rr=w19;
  *rr++ = w6;
  *rr++ = w10;
  /* #70: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) (*rr++)  = (w0*(*cs++));
  /* #71: @15 = dense(@19) */
  casadi_densify(w19, casadi_s0, w15, 0);
  /* #72: @16 = (@16+@15) */
  for (i=0, rr=w16, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #73: output[1][3] = @16 */
  if (res[1]) casadi_copy(w16, 4, res[1]+12);
  /* #74: @16 = zeros(2x4,4nz) */
  casadi_clear(w16, 4);
  /* #75: @17 = 00 */
  /* #76: @18 = 00 */
  /* #77: @6 = ones(2x1,1nz) */
  w6 = 1.;
  /* #78: {@10, NULL} = vertsplit(@6) */
  w10 = w6;
  /* #79: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #80: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #81: @10 = (@10/@7) */
  w10 /= w7;
  /* #82: @10 = (@1*@10) */
  w10  = (w1*w10);
  /* #83: @21 = 00 */
  /* #84: @7 = vertcat(@17, @18, @10, @21) */
  rr=(&w7);
  *rr++ = w10;
  /* #85: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #86: @10 = @7[0] */
  for (rr=(&w10), ss=(&w7)+0; ss!=(&w7)+1; ss+=1) *rr++ = *ss;
  /* #87: (@16[2] = @10) */
  for (rr=w16+2, ss=(&w10); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #88: @10 = ones(2x1,1nz) */
  w10 = 1.;
  /* #89: {NULL, @7} = vertsplit(@10) */
  w7 = w10;
  /* #90: @3 = (@3*@7) */
  w3 *= w7;
  /* #91: @5 = (@5*@7) */
  w5 *= w7;
  /* #92: @8 = (@8*@7) */
  w8 *= w7;
  /* #93: @17 = 00 */
  /* #94: @22 = vertcat(@3, @5, @8, @17) */
  rr=w22;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w8;
  /* #95: @22 = (@0*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w0*(*cs++));
  /* #96: @23 = @22[:3] */
  for (rr=w23, ss=w22+0; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #97: (@16[0, 1, 3] = @23) */
  for (cii=casadi_s1, rr=w16, ss=w23; cii!=casadi_s1+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #98: @15 = @16' */
  casadi_trans(w16,casadi_s3, w15, casadi_s2, iw);
  /* #99: @24 = dense(@15) */
  casadi_densify(w15, casadi_s2, w24, 0);
  /* #100: @25 = input[2][0] */
  casadi_copy(arg[2], 8, w25);
  /* #101: {@15, @16} = horzsplit(@25) */
  casadi_copy(w25, 4, w15);
  casadi_copy(w25+4, 4, w16);
  /* #102: {NULL, NULL, @3, @5} = vertsplit(@15) */
  w3 = w15[2];
  w5 = w15[3];
  /* #103: @15 = (@11*@5) */
  for (i=0, rr=w15, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w5);
  /* #104: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #105: @8 = (@5*@3) */
  w8  = (w5*w3);
  /* #106: @8 = (@1*@8) */
  w8  = (w1*w8);
  /* #107: @8 = (-@8) */
  w8 = (- w8 );
  /* #108: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #109: @3 = (@2*@3) */
  w3  = (w2*w3);
  /* #110: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #111: @17 = 00 */
  /* #112: @18 = 00 */
  /* #113: @19 = vertcat(@8, @3, @17, @18) */
  rr=w19;
  *rr++ = w8;
  *rr++ = w3;
  /* #114: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) (*rr++)  = (w0*(*cs++));
  /* #115: @14 = dense(@19) */
  casadi_densify(w19, casadi_s0, w14, 0);
  /* #116: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<4; ++i) (*rr++) += (*cs++);
  /* #117: {NULL, NULL, @8, @3} = vertsplit(@16) */
  w8 = w16[2];
  w3 = w16[3];
  /* #118: @11 = (@11*@3) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) *= w3;
  /* #119: @5 = (@5*@8) */
  w5 *= w8;
  /* #120: @5 = (@1*@5) */
  w5  = (w1*w5);
  /* #121: @5 = (-@5) */
  w5 = (- w5 );
  /* #122: @2 = (@2*@8) */
  w2 *= w8;
  /* #123: @1 = (@1*@2) */
  w1 *= w2;
  /* #124: @17 = 00 */
  /* #125: @18 = 00 */
  /* #126: @19 = vertcat(@5, @1, @17, @18) */
  rr=w19;
  *rr++ = w5;
  *rr++ = w1;
  /* #127: @19 = (@0*@19) */
  for (i=0, rr=w19, cs=w19; i<2; ++i) (*rr++)  = (w0*(*cs++));
  /* #128: @16 = dense(@19) */
  casadi_densify(w19, casadi_s0, w16, 0);
  /* #129: @11 = (@11+@16) */
  for (i=0, rr=w11, cs=w16; i<4; ++i) (*rr++) += (*cs++);
  /* #130: @25 = horzcat(@15, @11) */
  rr=w25;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #131: @24 = (@24+@25) */
  for (i=0, rr=w24, cs=w25; i<8; ++i) (*rr++) += (*cs++);
  /* #132: output[2][0] = @24 */
  casadi_copy(w24, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 75;
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 75*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
