/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rockit_model_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[15] = {6, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 5};
static const casadi_int casadi_s1[19] = {2, 6, 0, 2, 4, 6, 8, 9, 10, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s2[43] = {6, 6, 0, 6, 12, 18, 24, 29, 34, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 0, 1, 2, 3, 5};
static const casadi_int casadi_s3[7] = {4, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[33] = {6, 6, 0, 4, 8, 12, 16, 20, 24, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s8[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s9[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s10[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s11[8] = {6, 1, 0, 4, 2, 3, 4, 5};
static const casadi_int casadi_s12[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};

static const casadi_real casadi_c0[10] = {0., 0., 0., 0., 0., 0., 0., 0., 1., 1.};

/* rockit_model_expl_ode_hess:(i0[4],i1[4x4],i2[4x2],i3[4],i4[2],i5[7])->(o0[6x1,4nz],o1[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, w3, *w4=w+10, *w5=w+14, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+32, *w21=w+68, *w22=w+84, *w23=w+92, *w24=w+116, *w25=w+140, *w26=w+150, *w27=w+160, *w30=w+194, *w31=w+228, *w32=w+234, *w33=w+240, *w34=w+246, *w35=w+252, *w36=w+257, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, *w53=w+277, *w54=w+280, *w55=w+283, *w56=w+287, *w57=w+291, *w58=w+295, *w59=w+299;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[4][1] */
  w2 = arg[4] ? arg[4][1] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 4, w4);
  /* #5: @5 = (@3*@4) */
  for (i=0, rr=w5, cs=w4; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #6: {@3, @6, @7, NULL} = vertsplit(@5) */
  w3 = w5[0];
  w6 = w5[1];
  w7 = w5[2];
  /* #7: @8 = (@2*@6) */
  w8  = (w2*w6);
  /* #8: @9 = (@1*@8) */
  w9  = (w1*w8);
  /* #9: @10 = sin(@0) */
  w10 = sin( w0 );
  /* #10: @11 = (@2*@3) */
  w11  = (w2*w3);
  /* #11: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #12: @9 = (@9-@12) */
  w9 -= w12;
  /* #13: output[0][0] = @9 */
  if (res[0]) res[0][0] = w9;
  /* #14: @9 = cos(@0) */
  w9 = cos( w0 );
  /* #15: @12 = (@2*@9) */
  w12  = (w2*w9);
  /* #16: @13 = sin(@0) */
  w13 = sin( w0 );
  /* #17: @14 = (@2*@13) */
  w14  = (w2*w13);
  /* #18: @15 = input[4][0] */
  w15 = arg[4] ? arg[4][0] : 0;
  /* #19: @16 = tan(@15) */
  w16 = tan( w15 );
  /* #20: @17 = (@2*@16) */
  w17  = (w2*w16);
  /* #21: @18 = 0 */
  w18 = 0.;
  /* #22: @5 = vertcat(@12, @14, @17, @18) */
  rr=w5;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @12 = dot(@5, @4) */
  w12 = casadi_dot(4, w5, w4);
  /* #24: output[0][1] = @12 */
  if (res[0]) res[0][1] = w12;
  /* #25: @12 = (@2*@7) */
  w12  = (w2*w7);
  /* #26: @14 = cos(@15) */
  w14 = cos( w15 );
  /* #27: @17 = sq(@14) */
  w17 = casadi_sq( w14 );
  /* #28: @12 = (@12/@17) */
  w12 /= w17;
  /* #29: output[0][2] = @12 */
  if (res[0]) res[0][2] = w12;
  /* #30: @18 = (@16*@7) */
  w18  = (w16*w7);
  /* #31: @19 = (@13*@6) */
  w19  = (w13*w6);
  /* #32: @18 = (@18+@19) */
  w18 += w19;
  /* #33: @19 = (@9*@3) */
  w19  = (w9*w3);
  /* #34: @18 = (@18+@19) */
  w18 += w19;
  /* #35: output[0][3] = @18 */
  if (res[0]) res[0][3] = w18;
  /* #36: @20 = zeros(6x6) */
  casadi_clear(w20, 36);
  /* #37: @21 = input[1][0] */
  casadi_copy(arg[1], 16, w21);
  /* #38: @22 = input[2][0] */
  casadi_copy(arg[2], 8, w22);
  /* #39: @23 = horzcat(@21, @22) */
  rr=w23;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<8; ++i) *rr++ = *cs++;
  /* #40: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<6; ++i) for (j=0; j<4; ++j) rr[i+j*6] = *cs++;
  /* #41: @25 = 
  [[0, 0, 0, 0, 1, 00], 
   [0, 0, 0, 0, 00, 1]] */
  casadi_copy(casadi_c0, 10, w25);
  /* #42: @26 = @25' */
  casadi_trans(w25,casadi_s1, w26, casadi_s0, iw);
  /* #43: @27 = horzcat(@24, @26) */
  rr=w27;
  for (i=0, cs=w24; i<24; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<10; ++i) *rr++ = *cs++;
  /* #44: @28 = 00 */
  /* #45: @29 = 00 */
  /* #46: @30 = @27' */
  casadi_trans(w27,casadi_s2, w30, casadi_s2, iw);
  /* #47: {@31, @32, @33, @34, @35, @36} = horzsplit(@30) */
  casadi_copy(w30, 6, w31);
  casadi_copy(w30+6, 6, w32);
  casadi_copy(w30+12, 6, w33);
  casadi_copy(w30+18, 6, w34);
  casadi_copy(w30+24, 5, w35);
  casadi_copy(w30+29, 5, w36);
  /* #48: {NULL, NULL, @18, @19, @37, @38} = vertsplit(@31) */
  w18 = w31[2];
  w19 = w31[3];
  w37 = w31[4];
  w38 = w31[5];
  /* #49: @39 = (@6*@38) */
  w39  = (w6*w38);
  /* #50: @5 = (@4*@19) */
  for (i=0, rr=w5, cr=w4; i<4; ++i) (*rr++)  = ((*cr++)*w19);
  /* #51: {@19, @40, @41, NULL} = vertsplit(@5) */
  w19 = w5[0];
  w40 = w5[1];
  w41 = w5[2];
  /* #52: @42 = (@2*@40) */
  w42  = (w2*w40);
  /* #53: @39 = (@39+@42) */
  w39 += w42;
  /* #54: @39 = (@1*@39) */
  w39  = (w1*w39);
  /* #55: @42 = sin(@0) */
  w42 = sin( w0 );
  /* #56: @43 = (@42*@18) */
  w43  = (w42*w18);
  /* #57: @43 = (@8*@43) */
  w43  = (w8*w43);
  /* #58: @39 = (@39-@43) */
  w39 -= w43;
  /* #59: @43 = cos(@0) */
  w43 = cos( w0 );
  /* #60: @44 = (@43*@18) */
  w44  = (w43*w18);
  /* #61: @44 = (@11*@44) */
  w44  = (w11*w44);
  /* #62: @45 = (@3*@38) */
  w45  = (w3*w38);
  /* #63: @46 = (@2*@19) */
  w46  = (w2*w19);
  /* #64: @45 = (@45+@46) */
  w45 += w46;
  /* #65: @45 = (@10*@45) */
  w45  = (w10*w45);
  /* #66: @44 = (@44+@45) */
  w44 += w45;
  /* #67: @39 = (@39-@44) */
  w39 -= w44;
  /* #68: @44 = (@9*@38) */
  w44  = (w9*w38);
  /* #69: @45 = sin(@0) */
  w45 = sin( w0 );
  /* #70: @46 = (@45*@18) */
  w46  = (w45*w18);
  /* #71: @47 = (@2*@46) */
  w47  = (w2*w46);
  /* #72: @44 = (@44-@47) */
  w44 -= w47;
  /* #73: @47 = (@13*@38) */
  w47  = (w13*w38);
  /* #74: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #75: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #76: @48 = (@2*@18) */
  w48  = (w2*w18);
  /* #77: @47 = (@47+@48) */
  w47 += w48;
  /* #78: @48 = (@16*@38) */
  w48  = (w16*w38);
  /* #79: @49 = cos(@15) */
  w49 = cos( w15 );
  /* #80: @49 = sq(@49) */
  w49 = casadi_sq( w49 );
  /* #81: @50 = (@37/@49) */
  w50  = (w37/w49);
  /* #82: @51 = (@2*@50) */
  w51  = (w2*w50);
  /* #83: @48 = (@48+@51) */
  w48 += w51;
  /* #84: @52 = 00 */
  /* #85: @53 = vertcat(@44, @47, @48, @52) */
  rr=w53;
  *rr++ = w44;
  *rr++ = w47;
  *rr++ = w48;
  /* #86: @54 = project(@4) */
  casadi_sparsify(w4, w54, casadi_s3, 0);
  /* #87: @44 = dot(@53, @54) */
  w44 = casadi_dot(3, w53, w54);
  /* #88: @38 = (@7*@38) */
  w38  = (w7*w38);
  /* #89: @47 = (@2*@41) */
  w47  = (w2*w41);
  /* #90: @38 = (@38+@47) */
  w38 += w47;
  /* #91: @38 = (@38/@17) */
  w38 /= w17;
  /* #92: @12 = (@12/@17) */
  w12 /= w17;
  /* #93: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #94: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #95: @37 = (@15*@37) */
  w37  = (w15*w37);
  /* #96: @37 = (@14*@37) */
  w37  = (w14*w37);
  /* #97: @37 = (@12*@37) */
  w37  = (w12*w37);
  /* #98: @38 = (@38+@37) */
  w38 += w37;
  /* #99: @50 = (@7*@50) */
  w50  = (w7*w50);
  /* #100: @41 = (@16*@41) */
  w41  = (w16*w41);
  /* #101: @50 = (@50+@41) */
  w50 += w41;
  /* #102: @18 = (@6*@18) */
  w18  = (w6*w18);
  /* #103: @40 = (@13*@40) */
  w40  = (w13*w40);
  /* #104: @18 = (@18+@40) */
  w18 += w40;
  /* #105: @50 = (@50+@18) */
  w50 += w18;
  /* #106: @19 = (@9*@19) */
  w19  = (w9*w19);
  /* #107: @46 = (@3*@46) */
  w46  = (w3*w46);
  /* #108: @19 = (@19-@46) */
  w19 -= w46;
  /* #109: @50 = (@50+@19) */
  w50 += w19;
  /* #110: @5 = vertcat(@28, @29, @39, @44, @38, @50) */
  rr=w5;
  *rr++ = w39;
  *rr++ = w44;
  *rr++ = w38;
  *rr++ = w50;
  /* #111: {NULL, NULL, @39, @44, @38, @50} = vertsplit(@32) */
  w39 = w32[2];
  w44 = w32[3];
  w38 = w32[4];
  w50 = w32[5];
  /* #112: @19 = (@6*@50) */
  w19  = (w6*w50);
  /* #113: @55 = (@4*@44) */
  for (i=0, rr=w55, cr=w4; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #114: {@44, @46, @18, NULL} = vertsplit(@55) */
  w44 = w55[0];
  w46 = w55[1];
  w18 = w55[2];
  /* #115: @40 = (@2*@46) */
  w40  = (w2*w46);
  /* #116: @19 = (@19+@40) */
  w19 += w40;
  /* #117: @19 = (@1*@19) */
  w19  = (w1*w19);
  /* #118: @40 = (@42*@39) */
  w40  = (w42*w39);
  /* #119: @40 = (@8*@40) */
  w40  = (w8*w40);
  /* #120: @19 = (@19-@40) */
  w19 -= w40;
  /* #121: @40 = (@43*@39) */
  w40  = (w43*w39);
  /* #122: @40 = (@11*@40) */
  w40  = (w11*w40);
  /* #123: @41 = (@3*@50) */
  w41  = (w3*w50);
  /* #124: @37 = (@2*@44) */
  w37  = (w2*w44);
  /* #125: @41 = (@41+@37) */
  w41 += w37;
  /* #126: @41 = (@10*@41) */
  w41  = (w10*w41);
  /* #127: @40 = (@40+@41) */
  w40 += w41;
  /* #128: @19 = (@19-@40) */
  w19 -= w40;
  /* #129: @40 = (@9*@50) */
  w40  = (w9*w50);
  /* #130: @41 = (@45*@39) */
  w41  = (w45*w39);
  /* #131: @37 = (@2*@41) */
  w37  = (w2*w41);
  /* #132: @40 = (@40-@37) */
  w40 -= w37;
  /* #133: @37 = (@13*@50) */
  w37  = (w13*w50);
  /* #134: @39 = (@0*@39) */
  w39  = (w0*w39);
  /* #135: @47 = (@2*@39) */
  w47  = (w2*w39);
  /* #136: @37 = (@37+@47) */
  w37 += w47;
  /* #137: @47 = (@16*@50) */
  w47  = (w16*w50);
  /* #138: @48 = (@38/@49) */
  w48  = (w38/w49);
  /* #139: @51 = (@2*@48) */
  w51  = (w2*w48);
  /* #140: @47 = (@47+@51) */
  w47 += w51;
  /* #141: @52 = 00 */
  /* #142: @53 = vertcat(@40, @37, @47, @52) */
  rr=w53;
  *rr++ = w40;
  *rr++ = w37;
  *rr++ = w47;
  /* #143: @54 = project(@4) */
  casadi_sparsify(w4, w54, casadi_s3, 0);
  /* #144: @40 = dot(@53, @54) */
  w40 = casadi_dot(3, w53, w54);
  /* #145: @50 = (@7*@50) */
  w50  = (w7*w50);
  /* #146: @37 = (@2*@18) */
  w37  = (w2*w18);
  /* #147: @50 = (@50+@37) */
  w50 += w37;
  /* #148: @50 = (@50/@17) */
  w50 /= w17;
  /* #149: @38 = (@15*@38) */
  w38  = (w15*w38);
  /* #150: @38 = (@14*@38) */
  w38  = (w14*w38);
  /* #151: @38 = (@12*@38) */
  w38  = (w12*w38);
  /* #152: @50 = (@50+@38) */
  w50 += w38;
  /* #153: @48 = (@7*@48) */
  w48  = (w7*w48);
  /* #154: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #155: @48 = (@48+@18) */
  w48 += w18;
  /* #156: @39 = (@6*@39) */
  w39  = (w6*w39);
  /* #157: @46 = (@13*@46) */
  w46  = (w13*w46);
  /* #158: @39 = (@39+@46) */
  w39 += w46;
  /* #159: @48 = (@48+@39) */
  w48 += w39;
  /* #160: @44 = (@9*@44) */
  w44  = (w9*w44);
  /* #161: @41 = (@3*@41) */
  w41  = (w3*w41);
  /* #162: @44 = (@44-@41) */
  w44 -= w41;
  /* #163: @48 = (@48+@44) */
  w48 += w44;
  /* #164: @55 = vertcat(@28, @29, @19, @40, @50, @48) */
  rr=w55;
  *rr++ = w19;
  *rr++ = w40;
  *rr++ = w50;
  *rr++ = w48;
  /* #165: {NULL, NULL, @19, @40, @50, @48} = vertsplit(@33) */
  w19 = w33[2];
  w40 = w33[3];
  w50 = w33[4];
  w48 = w33[5];
  /* #166: @44 = (@6*@48) */
  w44  = (w6*w48);
  /* #167: @56 = (@4*@40) */
  for (i=0, rr=w56, cr=w4; i<4; ++i) (*rr++)  = ((*cr++)*w40);
  /* #168: {@40, @41, @39, NULL} = vertsplit(@56) */
  w40 = w56[0];
  w41 = w56[1];
  w39 = w56[2];
  /* #169: @46 = (@2*@41) */
  w46  = (w2*w41);
  /* #170: @44 = (@44+@46) */
  w44 += w46;
  /* #171: @44 = (@1*@44) */
  w44  = (w1*w44);
  /* #172: @46 = (@42*@19) */
  w46  = (w42*w19);
  /* #173: @46 = (@8*@46) */
  w46  = (w8*w46);
  /* #174: @44 = (@44-@46) */
  w44 -= w46;
  /* #175: @46 = (@43*@19) */
  w46  = (w43*w19);
  /* #176: @46 = (@11*@46) */
  w46  = (w11*w46);
  /* #177: @18 = (@3*@48) */
  w18  = (w3*w48);
  /* #178: @38 = (@2*@40) */
  w38  = (w2*w40);
  /* #179: @18 = (@18+@38) */
  w18 += w38;
  /* #180: @18 = (@10*@18) */
  w18  = (w10*w18);
  /* #181: @46 = (@46+@18) */
  w46 += w18;
  /* #182: @44 = (@44-@46) */
  w44 -= w46;
  /* #183: @46 = (@9*@48) */
  w46  = (w9*w48);
  /* #184: @18 = (@45*@19) */
  w18  = (w45*w19);
  /* #185: @38 = (@2*@18) */
  w38  = (w2*w18);
  /* #186: @46 = (@46-@38) */
  w46 -= w38;
  /* #187: @38 = (@13*@48) */
  w38  = (w13*w48);
  /* #188: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #189: @37 = (@2*@19) */
  w37  = (w2*w19);
  /* #190: @38 = (@38+@37) */
  w38 += w37;
  /* #191: @37 = (@16*@48) */
  w37  = (w16*w48);
  /* #192: @47 = (@50/@49) */
  w47  = (w50/w49);
  /* #193: @51 = (@2*@47) */
  w51  = (w2*w47);
  /* #194: @37 = (@37+@51) */
  w37 += w51;
  /* #195: @52 = 00 */
  /* #196: @53 = vertcat(@46, @38, @37, @52) */
  rr=w53;
  *rr++ = w46;
  *rr++ = w38;
  *rr++ = w37;
  /* #197: @54 = project(@4) */
  casadi_sparsify(w4, w54, casadi_s3, 0);
  /* #198: @46 = dot(@53, @54) */
  w46 = casadi_dot(3, w53, w54);
  /* #199: @48 = (@7*@48) */
  w48  = (w7*w48);
  /* #200: @38 = (@2*@39) */
  w38  = (w2*w39);
  /* #201: @48 = (@48+@38) */
  w48 += w38;
  /* #202: @48 = (@48/@17) */
  w48 /= w17;
  /* #203: @50 = (@15*@50) */
  w50  = (w15*w50);
  /* #204: @50 = (@14*@50) */
  w50  = (w14*w50);
  /* #205: @50 = (@12*@50) */
  w50  = (w12*w50);
  /* #206: @48 = (@48+@50) */
  w48 += w50;
  /* #207: @47 = (@7*@47) */
  w47  = (w7*w47);
  /* #208: @39 = (@16*@39) */
  w39  = (w16*w39);
  /* #209: @47 = (@47+@39) */
  w47 += w39;
  /* #210: @19 = (@6*@19) */
  w19  = (w6*w19);
  /* #211: @41 = (@13*@41) */
  w41  = (w13*w41);
  /* #212: @19 = (@19+@41) */
  w19 += w41;
  /* #213: @47 = (@47+@19) */
  w47 += w19;
  /* #214: @40 = (@9*@40) */
  w40  = (w9*w40);
  /* #215: @18 = (@3*@18) */
  w18  = (w3*w18);
  /* #216: @40 = (@40-@18) */
  w40 -= w18;
  /* #217: @47 = (@47+@40) */
  w47 += w40;
  /* #218: @56 = vertcat(@28, @29, @44, @46, @48, @47) */
  rr=w56;
  *rr++ = w44;
  *rr++ = w46;
  *rr++ = w48;
  *rr++ = w47;
  /* #219: {NULL, NULL, @44, @46, @48, @47} = vertsplit(@34) */
  w44 = w34[2];
  w46 = w34[3];
  w48 = w34[4];
  w47 = w34[5];
  /* #220: @40 = (@6*@47) */
  w40  = (w6*w47);
  /* #221: @57 = (@4*@46) */
  for (i=0, rr=w57, cr=w4; i<4; ++i) (*rr++)  = ((*cr++)*w46);
  /* #222: {@46, @18, @19, NULL} = vertsplit(@57) */
  w46 = w57[0];
  w18 = w57[1];
  w19 = w57[2];
  /* #223: @41 = (@2*@18) */
  w41  = (w2*w18);
  /* #224: @40 = (@40+@41) */
  w40 += w41;
  /* #225: @40 = (@1*@40) */
  w40  = (w1*w40);
  /* #226: @41 = (@42*@44) */
  w41  = (w42*w44);
  /* #227: @41 = (@8*@41) */
  w41  = (w8*w41);
  /* #228: @40 = (@40-@41) */
  w40 -= w41;
  /* #229: @41 = (@43*@44) */
  w41  = (w43*w44);
  /* #230: @41 = (@11*@41) */
  w41  = (w11*w41);
  /* #231: @39 = (@3*@47) */
  w39  = (w3*w47);
  /* #232: @50 = (@2*@46) */
  w50  = (w2*w46);
  /* #233: @39 = (@39+@50) */
  w39 += w50;
  /* #234: @39 = (@10*@39) */
  w39  = (w10*w39);
  /* #235: @41 = (@41+@39) */
  w41 += w39;
  /* #236: @40 = (@40-@41) */
  w40 -= w41;
  /* #237: @41 = (@9*@47) */
  w41  = (w9*w47);
  /* #238: @39 = (@45*@44) */
  w39  = (w45*w44);
  /* #239: @50 = (@2*@39) */
  w50  = (w2*w39);
  /* #240: @41 = (@41-@50) */
  w41 -= w50;
  /* #241: @50 = (@13*@47) */
  w50  = (w13*w47);
  /* #242: @44 = (@0*@44) */
  w44  = (w0*w44);
  /* #243: @38 = (@2*@44) */
  w38  = (w2*w44);
  /* #244: @50 = (@50+@38) */
  w50 += w38;
  /* #245: @38 = (@16*@47) */
  w38  = (w16*w47);
  /* #246: @37 = (@48/@49) */
  w37  = (w48/w49);
  /* #247: @51 = (@2*@37) */
  w51  = (w2*w37);
  /* #248: @38 = (@38+@51) */
  w38 += w51;
  /* #249: @52 = 00 */
  /* #250: @53 = vertcat(@41, @50, @38, @52) */
  rr=w53;
  *rr++ = w41;
  *rr++ = w50;
  *rr++ = w38;
  /* #251: @54 = project(@4) */
  casadi_sparsify(w4, w54, casadi_s3, 0);
  /* #252: @41 = dot(@53, @54) */
  w41 = casadi_dot(3, w53, w54);
  /* #253: @47 = (@7*@47) */
  w47  = (w7*w47);
  /* #254: @50 = (@2*@19) */
  w50  = (w2*w19);
  /* #255: @47 = (@47+@50) */
  w47 += w50;
  /* #256: @47 = (@47/@17) */
  w47 /= w17;
  /* #257: @48 = (@15*@48) */
  w48  = (w15*w48);
  /* #258: @48 = (@14*@48) */
  w48  = (w14*w48);
  /* #259: @48 = (@12*@48) */
  w48  = (w12*w48);
  /* #260: @47 = (@47+@48) */
  w47 += w48;
  /* #261: @37 = (@7*@37) */
  w37  = (w7*w37);
  /* #262: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #263: @37 = (@37+@19) */
  w37 += w19;
  /* #264: @44 = (@6*@44) */
  w44  = (w6*w44);
  /* #265: @18 = (@13*@18) */
  w18  = (w13*w18);
  /* #266: @44 = (@44+@18) */
  w44 += w18;
  /* #267: @37 = (@37+@44) */
  w37 += w44;
  /* #268: @46 = (@9*@46) */
  w46  = (w9*w46);
  /* #269: @39 = (@3*@39) */
  w39  = (w3*w39);
  /* #270: @46 = (@46-@39) */
  w46 -= w39;
  /* #271: @37 = (@37+@46) */
  w37 += w46;
  /* #272: @57 = vertcat(@28, @29, @40, @41, @47, @37) */
  rr=w57;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w47;
  *rr++ = w37;
  /* #273: {NULL, NULL, @40, @41, @47, NULL} = vertsplit(@35) */
  w40 = w35[2];
  w41 = w35[3];
  w47 = w35[4];
  /* #274: @58 = (@4*@41) */
  for (i=0, rr=w58, cr=w4; i<4; ++i) (*rr++)  = ((*cr++)*w41);
  /* #275: {@41, @37, @46, NULL} = vertsplit(@58) */
  w41 = w58[0];
  w37 = w58[1];
  w46 = w58[2];
  /* #276: @39 = (@2*@37) */
  w39  = (w2*w37);
  /* #277: @39 = (@1*@39) */
  w39  = (w1*w39);
  /* #278: @44 = (@42*@40) */
  w44  = (w42*w40);
  /* #279: @44 = (@8*@44) */
  w44  = (w8*w44);
  /* #280: @39 = (@39-@44) */
  w39 -= w44;
  /* #281: @44 = (@43*@40) */
  w44  = (w43*w40);
  /* #282: @44 = (@11*@44) */
  w44  = (w11*w44);
  /* #283: @18 = (@2*@41) */
  w18  = (w2*w41);
  /* #284: @18 = (@10*@18) */
  w18  = (w10*w18);
  /* #285: @44 = (@44+@18) */
  w44 += w18;
  /* #286: @39 = (@39-@44) */
  w39 -= w44;
  /* #287: @44 = (@45*@40) */
  w44  = (w45*w40);
  /* #288: @18 = (@2*@44) */
  w18  = (w2*w44);
  /* #289: @18 = (-@18) */
  w18 = (- w18 );
  /* #290: @40 = (@0*@40) */
  w40  = (w0*w40);
  /* #291: @19 = (@2*@40) */
  w19  = (w2*w40);
  /* #292: @49 = (@47/@49) */
  w49  = (w47/w49);
  /* #293: @48 = (@2*@49) */
  w48  = (w2*w49);
  /* #294: @52 = 00 */
  /* #295: @53 = vertcat(@18, @19, @48, @52) */
  rr=w53;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w48;
  /* #296: @54 = project(@4) */
  casadi_sparsify(w4, w54, casadi_s3, 0);
  /* #297: @18 = dot(@53, @54) */
  w18 = casadi_dot(3, w53, w54);
  /* #298: @19 = (@2*@46) */
  w19  = (w2*w46);
  /* #299: @19 = (@19/@17) */
  w19 /= w17;
  /* #300: @15 = (@15*@47) */
  w15 *= w47;
  /* #301: @14 = (@14*@15) */
  w14 *= w15;
  /* #302: @12 = (@12*@14) */
  w12 *= w14;
  /* #303: @19 = (@19+@12) */
  w19 += w12;
  /* #304: @49 = (@7*@49) */
  w49  = (w7*w49);
  /* #305: @46 = (@16*@46) */
  w46  = (w16*w46);
  /* #306: @49 = (@49+@46) */
  w49 += w46;
  /* #307: @40 = (@6*@40) */
  w40  = (w6*w40);
  /* #308: @37 = (@13*@37) */
  w37  = (w13*w37);
  /* #309: @40 = (@40+@37) */
  w40 += w37;
  /* #310: @49 = (@49+@40) */
  w49 += w40;
  /* #311: @41 = (@9*@41) */
  w41  = (w9*w41);
  /* #312: @44 = (@3*@44) */
  w44  = (w3*w44);
  /* #313: @41 = (@41-@44) */
  w41 -= w44;
  /* #314: @49 = (@49+@41) */
  w49 += w41;
  /* #315: @58 = vertcat(@28, @29, @39, @18, @19, @49) */
  rr=w58;
  *rr++ = w39;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w49;
  /* #316: {NULL, NULL, @39, @18, NULL, @19} = vertsplit(@36) */
  w39 = w36[2];
  w18 = w36[3];
  w19 = w36[4];
  /* #317: @49 = (@6*@19) */
  w49  = (w6*w19);
  /* #318: @59 = (@4*@18) */
  for (i=0, rr=w59, cr=w4; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #319: {@18, @41, @44, NULL} = vertsplit(@59) */
  w18 = w59[0];
  w41 = w59[1];
  w44 = w59[2];
  /* #320: @40 = (@2*@41) */
  w40  = (w2*w41);
  /* #321: @49 = (@49+@40) */
  w49 += w40;
  /* #322: @1 = (@1*@49) */
  w1 *= w49;
  /* #323: @42 = (@42*@39) */
  w42 *= w39;
  /* #324: @8 = (@8*@42) */
  w8 *= w42;
  /* #325: @1 = (@1-@8) */
  w1 -= w8;
  /* #326: @43 = (@43*@39) */
  w43 *= w39;
  /* #327: @11 = (@11*@43) */
  w11 *= w43;
  /* #328: @43 = (@3*@19) */
  w43  = (w3*w19);
  /* #329: @8 = (@2*@18) */
  w8  = (w2*w18);
  /* #330: @43 = (@43+@8) */
  w43 += w8;
  /* #331: @10 = (@10*@43) */
  w10 *= w43;
  /* #332: @11 = (@11+@10) */
  w11 += w10;
  /* #333: @1 = (@1-@11) */
  w1 -= w11;
  /* #334: @11 = (@9*@19) */
  w11  = (w9*w19);
  /* #335: @45 = (@45*@39) */
  w45 *= w39;
  /* #336: @10 = (@2*@45) */
  w10  = (w2*w45);
  /* #337: @11 = (@11-@10) */
  w11 -= w10;
  /* #338: @10 = (@13*@19) */
  w10  = (w13*w19);
  /* #339: @0 = (@0*@39) */
  w0 *= w39;
  /* #340: @39 = (@2*@0) */
  w39  = (w2*w0);
  /* #341: @10 = (@10+@39) */
  w10 += w39;
  /* #342: @39 = (@16*@19) */
  w39  = (w16*w19);
  /* #343: @52 = 00 */
  /* #344: @53 = vertcat(@11, @10, @39, @52) */
  rr=w53;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w39;
  /* #345: @54 = project(@4) */
  casadi_sparsify(w4, w54, casadi_s3, 0);
  /* #346: @11 = dot(@53, @54) */
  w11 = casadi_dot(3, w53, w54);
  /* #347: @7 = (@7*@19) */
  w7 *= w19;
  /* #348: @2 = (@2*@44) */
  w2 *= w44;
  /* #349: @7 = (@7+@2) */
  w7 += w2;
  /* #350: @7 = (@7/@17) */
  w7 /= w17;
  /* #351: @16 = (@16*@44) */
  w16 *= w44;
  /* #352: @6 = (@6*@0) */
  w6 *= w0;
  /* #353: @13 = (@13*@41) */
  w13 *= w41;
  /* #354: @6 = (@6+@13) */
  w6 += w13;
  /* #355: @16 = (@16+@6) */
  w16 += w6;
  /* #356: @9 = (@9*@18) */
  w9 *= w18;
  /* #357: @3 = (@3*@45) */
  w3 *= w45;
  /* #358: @9 = (@9-@3) */
  w9 -= w3;
  /* #359: @16 = (@16+@9) */
  w16 += w9;
  /* #360: @4 = vertcat(@28, @29, @1, @11, @7, @16) */
  rr=w4;
  *rr++ = w1;
  *rr++ = w11;
  *rr++ = w7;
  *rr++ = w16;
  /* #361: @24 = horzcat(@5, @55, @56, @57, @58, @4) */
  rr=w24;
  for (i=0, cs=w5; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w56; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w57; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w58; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<4; ++i) *rr++ = *cs++;
  /* #362: @20 = mac(@27,@24,@20) */
  casadi_mtimes(w27, casadi_s2, w24, casadi_s5, w20, casadi_s4, w, 0);
  /* #363: @1 = @20[0] */
  for (rr=(&w1), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #364: output[1][0] = @1 */
  if (res[1]) res[1][0] = w1;
  /* #365: @1 = @20[1] */
  for (rr=(&w1), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #366: output[1][1] = @1 */
  if (res[1]) res[1][1] = w1;
  /* #367: @1 = @20[2] */
  for (rr=(&w1), ss=w20+2; ss!=w20+3; ss+=1) *rr++ = *ss;
  /* #368: output[1][2] = @1 */
  if (res[1]) res[1][2] = w1;
  /* #369: @1 = @20[3] */
  for (rr=(&w1), ss=w20+3; ss!=w20+4; ss+=1) *rr++ = *ss;
  /* #370: output[1][3] = @1 */
  if (res[1]) res[1][3] = w1;
  /* #371: @1 = @20[4] */
  for (rr=(&w1), ss=w20+4; ss!=w20+5; ss+=1) *rr++ = *ss;
  /* #372: output[1][4] = @1 */
  if (res[1]) res[1][4] = w1;
  /* #373: @1 = @20[5] */
  for (rr=(&w1), ss=w20+5; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #374: output[1][5] = @1 */
  if (res[1]) res[1][5] = w1;
  /* #375: @1 = @20[7] */
  for (rr=(&w1), ss=w20+7; ss!=w20+8; ss+=1) *rr++ = *ss;
  /* #376: output[1][6] = @1 */
  if (res[1]) res[1][6] = w1;
  /* #377: @1 = @20[8] */
  for (rr=(&w1), ss=w20+8; ss!=w20+9; ss+=1) *rr++ = *ss;
  /* #378: output[1][7] = @1 */
  if (res[1]) res[1][7] = w1;
  /* #379: @1 = @20[9] */
  for (rr=(&w1), ss=w20+9; ss!=w20+10; ss+=1) *rr++ = *ss;
  /* #380: output[1][8] = @1 */
  if (res[1]) res[1][8] = w1;
  /* #381: @1 = @20[10] */
  for (rr=(&w1), ss=w20+10; ss!=w20+11; ss+=1) *rr++ = *ss;
  /* #382: output[1][9] = @1 */
  if (res[1]) res[1][9] = w1;
  /* #383: @1 = @20[11] */
  for (rr=(&w1), ss=w20+11; ss!=w20+12; ss+=1) *rr++ = *ss;
  /* #384: output[1][10] = @1 */
  if (res[1]) res[1][10] = w1;
  /* #385: @1 = @20[14] */
  for (rr=(&w1), ss=w20+14; ss!=w20+15; ss+=1) *rr++ = *ss;
  /* #386: output[1][11] = @1 */
  if (res[1]) res[1][11] = w1;
  /* #387: @1 = @20[15] */
  for (rr=(&w1), ss=w20+15; ss!=w20+16; ss+=1) *rr++ = *ss;
  /* #388: output[1][12] = @1 */
  if (res[1]) res[1][12] = w1;
  /* #389: @1 = @20[16] */
  for (rr=(&w1), ss=w20+16; ss!=w20+17; ss+=1) *rr++ = *ss;
  /* #390: output[1][13] = @1 */
  if (res[1]) res[1][13] = w1;
  /* #391: @1 = @20[17] */
  for (rr=(&w1), ss=w20+17; ss!=w20+18; ss+=1) *rr++ = *ss;
  /* #392: output[1][14] = @1 */
  if (res[1]) res[1][14] = w1;
  /* #393: @1 = @20[21] */
  for (rr=(&w1), ss=w20+21; ss!=w20+22; ss+=1) *rr++ = *ss;
  /* #394: output[1][15] = @1 */
  if (res[1]) res[1][15] = w1;
  /* #395: @1 = @20[22] */
  for (rr=(&w1), ss=w20+22; ss!=w20+23; ss+=1) *rr++ = *ss;
  /* #396: output[1][16] = @1 */
  if (res[1]) res[1][16] = w1;
  /* #397: @1 = @20[23] */
  for (rr=(&w1), ss=w20+23; ss!=w20+24; ss+=1) *rr++ = *ss;
  /* #398: output[1][17] = @1 */
  if (res[1]) res[1][17] = w1;
  /* #399: @1 = @20[28] */
  for (rr=(&w1), ss=w20+28; ss!=w20+29; ss+=1) *rr++ = *ss;
  /* #400: output[1][18] = @1 */
  if (res[1]) res[1][18] = w1;
  /* #401: @1 = @20[29] */
  for (rr=(&w1), ss=w20+29; ss!=w20+30; ss+=1) *rr++ = *ss;
  /* #402: output[1][19] = @1 */
  if (res[1]) res[1][19] = w1;
  /* #403: @1 = @20[35] */
  for (rr=(&w1), ss=w20+35; ss!=w20+36; ss+=1) *rr++ = *ss;
  /* #404: output[1][20] = @1 */
  if (res[1]) res[1][20] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void rockit_model_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int rockit_model_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real rockit_model_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rockit_model_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s6;
    case 4: return casadi_s9;
    case 5: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rockit_model_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 303;
  return 0;
}

CASADI_SYMBOL_EXPORT int rockit_model_expl_ode_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 7*sizeof(casadi_int);
  if (sz_w) *sz_w = 303*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
